language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./gradlew clean dist
